# Generated by Django 4.2.7 on 2025-05-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hex color code for category badge', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='URL of the featured image', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_breaking',
            field=models.BooleanField(default=False, help_text='Mark as breaking news'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured article'),
        ),
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL of the avatar image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
